### ISSUE TITLE
Bare metal installation options

### ISSUE THREAD

**Issue by trymeouteh** [hudikhq/hoodik#107]
Please offer bare metal installation options

- Executable (Download in github releases)
- NIX package
- APT package

**Comment by htunlogic** [comment]
You can always compile the project yourself. Could you follow the steps (without the docker stuff) from the publish workflow action?

https://github.com/hudikhq/hoodik/blob/master/.github/workflows/publish.yml

I understand that could be better, and I will (eventually) add binary, apt, and rpm packages.
