### ISSUE TITLE
Invalid user error

### ISSUE THREAD

**Issue by vmsman** [hudikhq/hoodik#110]
Does the app create the cert file and the key or is that up to the user and if so, what should be used to generate them?  Whenever starting the app I get an invalid user error and I am using the internal sqlite database as discussed.  Am I supposed to create a user?  If so, how?
`
hoodik  | Starting Hoodik v1.1.0 on 0.0.0.0:5443
hoodik  | -- Using data_dir: /data
hoodik  | -- Using ssl cert: /data/my-cert-file.crt.pem
hoodik  | -- Using ssl key: /data/my-key-file.key.pem
hoodik  | -- RUST_LOG=Some("hoodik=debug,auth=debug,error=debug,entity=debug,storage=debug,context=debug,util=debug,cryptfns=debug,actix_web=debug")
`

**Comment by htunlogic** [comment]
If you do not provide an SSL cert, one (self-signed) will be created. The first user who registers will be assigned an admin role.
