### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by bradleyallanpatterson** [hudikhq/hoodik#111]
I just got my docker image working - I am new to docker.  I created an account and logged in and see these issues.

1. I get kicked with a few minutes.
2. Unable to upload any file - error displayed error 401 auth::data::claims|no_claims
3. Unable to create folder - auth::data::claims|no_claims

Side note I cannot find how to link the /data folder to a samba share.  Is this possible?

**Comment by bradleyallanpatterson** [comment]
So initial setup was using Docker on Linux Mint 22, next moved to my Mac M2 silicon and both do same thing as described- so I’m doing the same thing want Evers wrong.

I also notify that the storage is not showing anything.

Also there’s is an error, red square in top right corner saying something is null.  This happens and screen goes blank and must relogin.

**Comment by htunlogic** [comment]
It seems like your `APP_URL` and `APP_COOKIE_DOMAIN` are mismatched. 

Please review the [example configuration](https://github.com/hudikhq/hoodik/blob/master/.env.example) to see what settings you need to make it work.

The application uses cookies to authenticate. Once you log in, the application sets the cookie for the `APP_COOKIE_DOMAIN`, which is usually the same as `APP_URL`. If you access the application through a different address, your cookie won't be valid.

Also, if you are using the application without SSL, make sure that you set `COOKIE_SECURE` to `false`.
