### ISSUE TITLE
Add sharing capability for files

### ISSUE THREAD

**Issue by htunlogic** [hudikhq/hoodik#3]
FIles can be shared between users on the platform.

User can select file that he wants to share, and then click share button and insert users email, if user exists on the platform UserFiles entity should be created for that other user and he should get a notification that the file was shared with him.

Shares will be displayed on a separate page, there should be "Shared with me" and "My shares" where user would be able to see files shared with him and also files he shared.

Shares don't support sharing folders, only files can be selected to be shared.

Note: If user doesn't exist on the platform, user should be prompted that it cannot be directly shared and should be taken to sending a public link to the user that is not on the platform.

**Comment by thiphariel** [comment]
@htunlogic Hello there.
Is there any chance of seeing folders sharing one day? Its kind of must have feature for my personal usage and was wondering if it was planned or put aside on purpose.

Thanks!

**Comment by UltiomDesign** [comment]
Hello now 3 years later, is there any plan on implementing folder sharing to hoodik ? It is still a must have for a file storage to also be able to share folders too as sometimes we have more than just 1 file to give out
It would also be wise to otherwise offer compression capacity (ex. select file+/folder and Compress into archive that can then be shared)

**Comment by htunlogic** [comment]
I am actually working on this feature right now. There will be a whole sharing feature account-to-account on the server and you will be able to share files, folders, create groups to share files and folders with, etc. With different roles.

There is a lot of work still left to do on that front, but hopefully it will be in the next version.
