### ISSUE TITLE
Registrations are still possible, although registration is not allowed

### ISSUE THREAD

**Issue by Joly0** [hudikhq/hoodik#62]
Hey, i just set this up on my unraid server and noticed, that registration is still possible, although i have disabled registration in settings
![grafik](https://github.com/hudikhq/hoodik/assets/13993216/ab491d5d-2a60-42ef-a14e-6276c4f1574e)

**Comment by Joly0** [comment]
Ok, nvm, idk whats going on. Now trying to setup a different account it tells me "invalid_email" after the whole registration process, which is also quite weird for an end user to go through the whole process just to end up on the first page to have that information. I guess would be better to check first, if registration is allowed and if the mail is valid and then process further?

**Comment by Joly0** [comment]
And as a side note, although i got the notification "invalid_email" it still created the account and i was able to login with that user normally

**Comment by Joly0** [comment]
And another side-note. Creating yet another account after the last one, i didnt even get a notification that the mail was invalid and just got logged in straight away

**Comment by Aruscha** [comment]
I also have the same problem.
I understand that the software is on version 1, but this problem makes me stop using the software.
It is too big a security risk that strangers tend to be able to create an account.

**Comment by htunlogic** [comment]
Hey, thanks for reporting this. I will take a look and fix it some time next week.
