### ISSUE TITLE
Uploading files larger than a few MB does not work (correctly?)

### ISSUE THREAD

**Issue by Joly0** [hudikhq/hoodik#69]
Hey, i noticed, that uploading files which are larger than a few MB does not work and i only get error messages if i try to
![grafik](https://github.com/hudikhq/hoodik/assets/13993216/d1283963-2bfb-4322-a956-473e4bc8c278)
![grafik](https://github.com/hudikhq/hoodik/assets/13993216/56ece59c-0b3c-4eee-b010-71ac4a595f2f)
Smaller files do work though
![grafik](https://github.com/hudikhq/hoodik/assets/13993216/999908e2-ae87-4433-8133-592ca83de66c)

**Comment by Joly0** [comment]
I am using Firefox version 118.0.1 and in dev console i get these errors:
![grafik](https://github.com/hudikhq/hoodik/assets/13993216/2d750d67-1cea-4dc8-908b-9ac1e57ec36a)
The first 4 are there when loading the page, the last one appears after trying to upload a file

**Comment by Joly0** [comment]
Response for the get request is this:
![grafik](https://github.com/hudikhq/hoodik/assets/13993216/d79670fd-0dcf-4824-85ac-e01b3d5e768e)

**Comment by htunlogic** [comment]
Okay, noted, seems like this is a bug that will need quite some dedication to fix. Currently, Firefox is then not supported 😢

I labeled it as a bug and will get to it some time during this month when I get time to focus on it.
