### ISSUE TITLE
Removing the unraid-template completly from the repo

### ISSUE THREAD

**Issue by Joly0** [hudikhq/hoodik#70]
Hey, i have seen, that the unraid template is still visible in the git history of this project and it has some (i guess) sensitive informtion in it.
I´d suggest to run
`git filter-branch --tree-filter 'rm -f unraid-template.xml' HEAD`
followed by
`git push origin --force --all`
to completly remove that file from the git history and making it (afaik) unrecoverable.
Those commands should go through all git commits and remove that file completely.

The process is described here https://www.linkedin.com/pulse/how-remove-file-from-github-repository-has-already-been-daniel-awde

**Comment by htunlogic** [comment]
Thank you for noticing and informing me about this ❤️
