### ISSUE TITLE
Push container images to GHCR

### ISSUE THREAD

**Issue by onedr0p** [hudikhq/hoodik#77]
Dockerhub has pull rate limits and have also shown in recent history to be pretty hostile to open source developers.

Please consider publishing the container image to Github's container registry (GHCR) as well. Publishing the container image to GHCR also is integrated with Github and is shown under the packages section on your repo's landing page.

**Comment by htunlogic** [comment]
Good point, the app is now published on the GHCR as well.

**Comment by onedr0p** [comment]
You might need to make the package public, I don't see it here

https://github.com/orgs/hudikhq/packages?repo_name=hoodik
