### ISSUE TITLE
httputil: ReverseProxy read error during body copy: net/http: server replied with more than declared Content-Length; truncated

### ISSUE THREAD

**Issue by jakevis** [hudikhq/hoodik#80]
I am currently using a tailscale reverse proxy to serve up hoodik (https://tailscale.com/kb/1312/serve); and I am seeing this error when I am trying to download content (including image previews).

```httputil: ReverseProxy read error during body copy: net/http: server replied with more than declared Content-Length; truncated```

Debugging on hoodik itself didnt show any errors or warnings; and that is the only error I get in the proxy logs. The result however is messages like:

![image](https://github.com/hudikhq/hoodik/assets/10895705/d82b9d2f-27b3-4c55-b966-788e7676bb78)

and

![image](https://github.com/hudikhq/hoodik/assets/10895705/6b0e8b93-2334-46a1-9d12-c2bcf56a7fe6)

Removing the reverse proxy fixes it - however I then run into issues with certificate validity and I cant seem to get hoodik to accept certs from letsencrypt.. but I would really prefer to get the reverse proxy working anyway.

Anyone seen this before?

**Comment by htunlogic** [comment]
Hi, 
I had trouble trying to reproduce this, but when I finally did the fix was pretty easy.

Try updating to version 1.1.1 and report back if the error persists.

**Comment by jakevis** [comment]
Works a charm! - confirmed fully functional

thanks @htunlogic
