### ISSUE TITLE
Have a way to disable the ssl and allow http

### ISSUE THREAD

**Issue by johnlabor** [hudikhq/hoodik#93]
Hi,

Is there a way for me to completely disable ssl on hoodik with pure http connections? If I want to use nginx proxy manager (npm), I would rather let docker doesnt expose any port and use npm to directly connect to it. The npm can be used as a ssl termination point directly, not on hoodik. Right now I have to either provide a pair of signed ca certs myself, or I have to make npm do a 1st round termination, then use the self-generated certs from hoodik for a second pair of termination, which is rather confusing and unnecessary imho.

Thanks.

**Comment by jgkawell** [comment]
I would like this feature as well. I run all my services in k8s with my ingress handled by Istio and it routes securely to services like hoodik using a sidecar and mTLS. This means none of my services need to bother with TLS at all since termination happens on ingress.

**Comment by htunlogic** [comment]
Disabling SSL is now available through the environment variable `SSL_DISABLED=true` as can be seen in the [example env file](https://github.com/hudikhq/hoodik/blob/7ce7378e2d7f65b6fdd0d1eac0fb1109c9c7b62d/.env.example#L75).

**Comment by UltiomDesign** [comment]
> Disabling SSL is now available through the environment variable `SSL_DISABLED=true` as can be seen in the [example env file](https://github.com/hudikhq/hoodik/blob/7ce7378e2d7f65b6fdd0d1eac0fb1109c9c7b62d/.env.example#L75).

Thank you this worked for using NPM but it would be useful to add it on the Setup Steps otherwise hard to figure out without digging in issues (And issues should not be documentation for technical difficulties but a way to address them in order to be more accessible for future users)
Maybe add a two tab one for Caddy & one for NPM

**Comment by htunlogic** [comment]
@UltiomDesign, you are absolutely correct. I am working on getting the documentation in a better order, a couple of commits before I've included the full rundown of env variables in the readme, and have started to write blogs/guides on the project website https://hoodik.io
