### ISSUE TITLE
It's possible to mount existing storage?

### ISSUE THREAD

**Issue by PrzemekSkw** [hudikhq/hoodik#96]
Hello, 
I install Hoodik on my unraid server and want to make sharing links for my files. I have separate share folder for hoodik but want to share existing media files. It's possible?
Regards.

**Comment by htunlogic** [comment]
Hi @PrzemekSkw, 
Unfortunately, no. 
You'll have to upload whatever you want to share through Hoodik first.
It has its storage because all the data from it is encrypted and chunked, and it doesn't understand regular file formats.
